name: face_recognition_app
description: A Flutter application for face recognition using Laravel API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  camera: ^0.11.2+1
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  image: ^4.5.4
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true